openapi: 3.0.0
info:
  title: API de Gestión de Usuarios - GEX
  description: API para gestionar usuarios dentro del sistema GEX. Diseñada para facilitar futuras ampliaciones.
  version: "1.0.0"
servers:
  - url: https://api.gex.com
    description: Servidor de producción
  - url: https://api.staging.gex.com
    description: Servidor de pruebas
paths:
  /usuario:
    $ref: "endpoints/usuarios.yaml#/paths/~1usuario"
  /usuario/{id}:
    $ref: "endpoints/usuarios.yaml#/paths/~1usuario~1{id}"
  /usuario/resetear-clave:
    $ref: "endpoints/usuarios.yaml#/paths/~1usuario~1resetear-clave"
